# Generated by Django 6.1.1 on 2026-09-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('telephone', models.TextField()),
                ('Date_birth', models.DateField()),
                ('Loyalty_status', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bowling',
        ),
    ]
