# Generated by Django 6.1.1 on 2026-09-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_client_delete_bowling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер дорожки')),
                ('kind', models.TextField(verbose_name='Тип дорожки')),
                ('status', models.TextField(verbose_name='Статус')),
                ('price', models.IntegerField(verbose_name='Стоимость часа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Loyalty_status',
            field=models.TextField(verbose_name='Статус лояльности'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('price', models.IntegerField(verbose_name='Общая стоимость')),
                ('status', models.TextField(verbose_name='Статус брони')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bowling.client')),
                ('lane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bowling.lane')),
            ],
        ),
    ]
