# Generated by Django 6.1.1 on 2026-09-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_lane_alter_client_options_alter_client_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь'},
        ),
    ]
