# Generated by Django 6.1.1 on 2026-09-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Бронь'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lane',
        ),
    ]
