# Generated by Django 6.1.1 on 2026-09-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0005_alter_booking_options_remove_booking_lane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lane',
            options={'verbose_name': 'Дорожка', 'verbose_name_plural': 'Дорожки'},
        ),
        migrations.AddField(
            model_name='booking',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bowling.lane'),
        ),
    ]
