# Generated by Django 6.1.1 on 2026-09-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0006_alter_lane_options_booking_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lane',
        ),
    ]
