# Generated by Django 6.1.1 on 2026-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0008_booking_lane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('сategory', models.TextField(verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('unit_measurement', models.TextField(verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
