# Generated by Django 6.1.1 on 2026-09-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookinAndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price_moment_order', models.IntegerField(verbose_name='Цена_на_момент_заказа')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bowling.booking')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bowling.service')),
            ],
            options={
                'verbose_name': 'Услуга в бронировании',
                'verbose_name_plural': 'Услуги в бронировании',
            },
        ),
    ]
